SELECT 
    PRODUCT_ID, 
    PRODUCT_NAME,
    PRODUCT_CD,
    CATEGORY,
    PRICE
FROM (SELECT * FROM FOOD_PRODUCT ORDER BY PRICE DESC)
WHERE ROWNUM = 1;

SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CD,
    CATEGORY,
    PRICE
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);