SELECT 
    ANIMAL_ID, 
    NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID FROM ANIMAL_INS
)
ORDER BY ANIMAL_ID;


SELECT 
    A.ANIMAL_ID,
    A.NAME
FROM (
    SELECT ANIMAL_ID,NAME FROM ANIMAL_OUTS
    MINUS
    SELECT ANIMAL_ID,NAME FROM ANIMAL_INS
) A;