SELECT
    AI.NAME,
    AI.DATETIME
FROM
    ANIMAL_INS AI
WHERE
    NOT EXISTS(
        SELECT AO.ANIMAL_ID
        FROM ANIMAL_OUTS AO
        WHERE AI.ANIMAL_ID = AO.ANIMAL_ID
    )
ORDER BY AI.DATETIME
FETCH FIRST 3 ROWS ONLY;